# Generated by Django 3.2.12 on 2022-07-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
