# Generated by Django 3.2.12 on 2022-07-05 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='owner',
        ),
    ]
