# Generated by Django 3.2.12 on 2022-07-05 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_auto_20220705_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category_id',
        ),
    ]
