# Generated by Django 3.2.12 on 2022-07-11 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_auto_20220705_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_of_transaction',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
