# Generated by Django 3.2.12 on 2022-07-12 00:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cash', '0005_alter_transaction_time_of_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('start_date', models.DateField(default=datetime.date(2022, 7, 12))),
                ('to_date', models.DateField(default=datetime.date(2022, 7, 12))),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='budget_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cash.budget'),
        ),
    ]
