# Generated by Django 3.2.12 on 2022-07-04 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0007_alter_category_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='category_id',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, to='cash.category'),
            preserve_default=False,
        ),
    ]
